### ISSUE TITLE
Same host different port

### ISSUE THREAD

**Issue by samuelmanzanera** [alajmo/sake#22]
Hello

I've been playing with sake which is really good but I encountered a case where I have few servers on the same IP but with several SSH ports. 

And sake throws an error

```
$ sake check
Found configuration errors:

error: found duplicate host `X.X.X.X` for the following servers
```

which is inconvenient because SSH supports it

**Comment by alajmo** [comment]
Thanks, I'll look to remove this limitation so you can specify servers with the same host.

**Comment by alajmo** [comment]
I've removed the limitation of duplicate hosts (see release v0.10.2), please re-open if the error persists.
