### ISSUE TITLE
Option to disable "Running" output

### ISSUE THREAD

**Issue by tbnguyen1407** [alajmo/sake#34]
## Is your feature request related to a problem? Please describe

Similar to `alajmo/mani` project, output from `sake` includes a `Running` spinner, which is also present when directed to file.

## Describe the solution you'd like

Add an option to disable the `Running` spinner (-s, --silent).

## Additional context

I use and enjoy both projects ;)

**Comment by alajmo** [comment]
This should work now with [v0.12.0](https://github.com/alajmo/sake/releases/tag/v0.12.0).

```bash
sake run <task> -o table -S
```
