### ISSUE TITLE
Exec command with single quotes

### ISSUE THREAD

**Issue by enriquetoledano** [alajmo/sake#49]
Hi:

Maybe I'm not doing it right, but I don't know how to run a command with single quote in it.
When I run, for example:
`
sake exec -s server 'uname -r|awk -v FS='-' '{print $1}''
`

it fails with "Process exited with status 1".
I've tried with doble quote and "\\", but I can't find a way for it to work

Is there a way to do it?

Best regards

**Comment by alajmo** [comment]
`sake exec -s server "uname -r|awk -v FS='-' '{print $1}'"`

**Comment by alajmo** [comment]
You're correct, this seems to work correct:

```bash
sake exec -s log -o table $'uname -r | awk -v FS=\'-\' \'{print $1}\''

TASK [task-0] ***********************************************************

192.168.1.203 | 5.15.76

RECAP *******************************************************************

 192.168.1.203      ok=1  unreachable=0  ignored=0  failed=0  skipped=0
```

Use `$'my \'string\''` to escape characters

- https://wiki.bash-hackers.org/scripting/bashchanges#quoting_expansions_substitutions_and_related
- https://stackoverflow.com/a/16605140/1645369

**Comment by enriquetoledano** [comment]
Hi!

This method isn't working for me:

```
sake exec -s server -o table $'uname -r | awk -v FS=\'-\' \'{print $1}\''

TASKS ***************************************************************************************************

 host       | task-0
------------+---------------------------------------------------------------
 x.x.x.x | awk: cmd. line:1: {print
            | awk: cmd. line:1:       ^ unexpected newline or end of string
            |
            | Process exited with status 1

RECAP ***************************************************************************************************

 x.x.x.x      ok=0  unreachable=0  ignored=0  failed=1  skipped=0
```
The only way I could make it work was:

 `sake exec -s server $'uname -r | awk -v FS=\'-\' "{print $ 1}"'`

That is, using doble quote for print and with a space between $ and number.

When defined as a task, it runs correctly when using:

```
  print-kernel:
    name: Kernel
    desc: Print kernel version
    spec: info
    target: all
    cmd: uname -r | awk -v FS='-' "{print $ 1}"
```
Thank you very much for your help!
